import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const garet = localFont({
  src:[
   { path:'./fonts/Garet-Book.otf',
    weight:'300',
 }   ,
 {
  path:'./fonts/Garet-Heavy.otf',
  weight:'600'
 }
  ]
}
)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={garet.className}>{children}</body>
    </html>
  );
}
