import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/sections/Navbar";
import Banner from "@/components/sections/Banner";
import Footer from "@/components/sections/Footer";


const garet = localFont({
  src:[
   { path:'./fonts/Garet-Book.otf',
    weight:'300',
 }   ,
 {
  path:'./fonts/Garet-Heavy.otf',
  weight:'600'
 }
  ]
}
)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={garet.className}>
      <Banner />
      <Navbar />
      <div className="overflow-x-hidden">
        {children}
      </div>
        </body>
        <footer>
        <Footer />
        </footer>
          
        
    </html>
  );
}
